// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKRNuUPB8Jy4PKljxtn5Xt7k8uzKpMxz8',
    appId: '1:453607465411:web:12ab0dd706b25816429d76',
    messagingSenderId: '453607465411',
    projectId: 'chat-app-5a53e',
    authDomain: 'chat-app-5a53e.firebaseapp.com',
    storageBucket: 'chat-app-5a53e.appspot.com',
    measurementId: 'G-84YS9FW7B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmLb7FXBneebusC_itsRPbZ5FsCiZSCD4',
    appId: '1:453607465411:android:f17c7d2140d7a6b5429d76',
    messagingSenderId: '453607465411',
    projectId: 'chat-app-5a53e',
    storageBucket: 'chat-app-5a53e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBjfcISqzbwJEmJcdm8xaZKkoZXl5VOOE',
    appId: '1:453607465411:ios:aff79aef2c334c48429d76',
    messagingSenderId: '453607465411',
    projectId: 'chat-app-5a53e',
    storageBucket: 'chat-app-5a53e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBjfcISqzbwJEmJcdm8xaZKkoZXl5VOOE',
    appId: '1:453607465411:ios:aff79aef2c334c48429d76',
    messagingSenderId: '453607465411',
    projectId: 'chat-app-5a53e',
    storageBucket: 'chat-app-5a53e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKRNuUPB8Jy4PKljxtn5Xt7k8uzKpMxz8',
    appId: '1:453607465411:web:5d20e28212fb09f4429d76',
    messagingSenderId: '453607465411',
    projectId: 'chat-app-5a53e',
    authDomain: 'chat-app-5a53e.firebaseapp.com',
    storageBucket: 'chat-app-5a53e.appspot.com',
    measurementId: 'G-BZFQ4BSEJ2',
  );
}
